ALTER TYPE "AgentTaskCategory" ADD VALUE 'OPTICAL' BEFORE 'OTHER';
ALTER TYPE "AgentTaskCategory" ADD VALUE 'MEDICATION' BEFORE 'OTHER';
ALTER TYPE "AgentTaskCategory" ADD VALUE 'REFERRALS' BEFORE 'OTHER';
